import {
  buildDashboardSummary,
  calculateEquipmentTimesheetCost,
  calculatePersonnelTimesheetDue,
} from "./calculations";
import type {
  CaisseTransaction,
  Chantier,
  Employee,
  Equipment,
  EquipmentTimesheet,
  GasoilEntry,
  GasoilExit,
  PersonnelAdvance,
  PersonnelTimesheet,
  Production,
  Supplier,
  User,
} from "./types";

export const users: User[] = [
  {
    id: "user-ali",
    name: "Ali BOUNOR",
    email: "ali@omotal.ma",
    role: "super_admin",
    chantierIds: ["chantier-genie-meknes"],
    active: true,
  },
  {
    id: "user-boubker",
    name: "Boubker",
    email: "direction@omotal.ma",
    role: "directeur",
    chantierIds: ["chantier-genie-meknes"],
    active: true,
  },
  {
    id: "user-ayoub",
    name: "Ayoub",
    email: "ayoub@omotal.ma",
    role: "pointeur",
    chantierIds: ["chantier-genie-meknes"],
    active: true,
  },
  {
    id: "user-comptable",
    name: "Comptable OMOTAL",
    email: "admin@omotal.ma",
    role: "comptable",
    chantierIds: ["chantier-genie-meknes"],
    active: true,
  },
  {
    id: "user-responsable",
    name: "Responsable chantier",
    email: "responsable@omotal.ma",
    role: "responsable_chantier",
    chantierIds: ["chantier-genie-meknes", "chantier-zaitoune"],
    active: true,
  },
];

export const chantiers: Chantier[] = [
  {
    id: "chantier-genie-meknes",
    name: "Genie Meknes AO 62/2026",
    code: "GM-62-2026",
    client: "Maitre d'ouvrage pilote",
    location: "Meknes",
    startedAt: "2026-05-01",
    expectedEndAt: "2026-12-20",
    marketAmountHt: 12800000,
    status: "en_cours",
    managerUserId: "user-ali",
  },
  {
    id: "chantier-zaitoune",
    name: "Chantier Zaitoune",
    code: "ZA-2026",
    client: "Commune partenaire",
    location: "Casablanca",
    startedAt: "2026-04-15",
    expectedEndAt: "2026-10-30",
    marketAmountHt: 7800000,
    status: "en_cours",
    managerUserId: "user-responsable",
  },
  {
    id: "chantier-berkane",
    name: "Chantier Berkane",
    code: "BK-2026",
    client: "Maitre d'ouvrage regional",
    location: "Berkane",
    startedAt: "2026-03-01",
    expectedEndAt: "2026-09-15",
    marketAmountHt: 9400000,
    status: "suspendu",
    managerUserId: "user-ali",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "supplier-station-nord",
    name: "Station Nord Meknes",
    type: "station",
    phone: "+212600000001",
    active: true,
  },
  {
    id: "supplier-location-atlas",
    name: "Location Atlas Engins",
    type: "loueur",
    phone: "+212600000002",
    active: true,
  },
];

export const equipment: Equipment[] = [
  {
    id: "equipment-pelle-01",
    designation: "Pelle CAT 320",
    type: "pelle",
    owner: "Location Atlas Engins",
    chantierId: "chantier-genie-meknes",
    billingMode: "heure",
    hourlyRate: 350,
    usualDriver: "Said",
    status: "mobilise",
  },
  {
    id: "equipment-niveleuse-01",
    designation: "Niveleuse 140K",
    type: "niveleuse",
    owner: "OMOTAL",
    chantierId: "chantier-genie-meknes",
    billingMode: "jour",
    dailyRate: 2600,
    usualDriver: "Mustapha",
    status: "mobilise",
  },
  {
    id: "equipment-camion-01",
    designation: "Camion 8x4",
    type: "camion",
    owner: "Transport partenaire",
    chantierId: "chantier-genie-meknes",
    billingMode: "heure",
    usualDriver: "Hamid",
    status: "mobilise",
  },
];

export const employees: Employee[] = [
  {
    id: "employee-omar",
    firstName: "Omar",
    lastName: "El Fassi",
    position: "Ouvrier",
    chantierId: "chantier-genie-meknes",
    remunerationType: "jour",
    dailySalary: 160,
    active: true,
  },
  {
    id: "employee-yassine",
    firstName: "Yassine",
    lastName: "Bennani",
    position: "Chef equipe",
    chantierId: "chantier-genie-meknes",
    remunerationType: "mois",
    monthlySalary: 5200,
    active: true,
  },
];

export const transactions: CaisseTransaction[] = [
  {
    id: "transaction-financement-01",
    date: "2026-05-10",
    chantierId: "chantier-genie-meknes",
    type: "credit",
    amount: 150000,
    paymentMode: "banque_omotal",
    category: "financement",
    description: "Alimentation chantier pilote",
    status: "valide",
    hasDocument: true,
    enteredByUserId: "user-comptable",
  },
  {
    id: "transaction-gasoil-01",
    date: "2026-05-11",
    chantierId: "chantier-genie-meknes",
    type: "debit",
    amount: 11800,
    paymentMode: "banque_omotal",
    category: "gasoil",
    description: "Achat gasoil Station Nord",
    personOrSupplier: "Station Nord Meknes",
    status: "valide",
    hasDocument: true,
    enteredByUserId: "user-comptable",
  },
  {
    id: "transaction-engin-01",
    date: "2026-05-18",
    chantierId: "chantier-genie-meknes",
    type: "debit",
    amount: 42000,
    paymentMode: "banque_omotal",
    category: "location_engins",
    description: "Acompte location engins",
    personOrSupplier: "Location Atlas Engins",
    status: "soumis",
    hasDocument: false,
    enteredByUserId: "user-comptable",
  },
];

export const gasoilEntries: GasoilEntry[] = [
  {
    id: "gasoil-entry-01",
    date: "2026-05-11",
    chantierId: "chantier-genie-meknes",
    supplierId: "supplier-station-nord",
    liters: 1000,
    unitPrice: 11.8,
    receiptNumber: "BR-001",
    status: "valide",
    hasDocument: true,
    enteredByUserId: "user-comptable",
  },
  {
    id: "gasoil-entry-02",
    date: "2026-05-18",
    chantierId: "chantier-genie-meknes",
    supplierId: "supplier-station-nord",
    liters: 600,
    unitPrice: 11.9,
    receiptNumber: "BR-002",
    status: "soumis",
    hasDocument: true,
    enteredByUserId: "user-comptable",
  },
];

export const gasoilExits: GasoilExit[] = [
  {
    id: "gasoil-exit-01",
    date: "2026-05-12",
    chantierId: "chantier-genie-meknes",
    equipmentId: "equipment-pelle-01",
    responsible: "Said",
    allocation: "production",
    liters: 120,
    unitPrice: 11.8,
    exitNumber: "BS-001",
    status: "valide",
    hasDocument: true,
    enteredByUserId: "user-ayoub",
  },
  {
    id: "gasoil-exit-02",
    date: "2026-05-13",
    chantierId: "chantier-genie-meknes",
    equipmentId: "equipment-niveleuse-01",
    responsible: "Mustapha",
    allocation: "production",
    liters: 90,
    unitPrice: 11.8,
    exitNumber: "BS-002",
    status: "soumis",
    hasDocument: true,
    enteredByUserId: "user-ayoub",
  },
  {
    id: "gasoil-exit-03",
    date: "2026-05-14",
    chantierId: "chantier-genie-meknes",
    responsible: "Depot",
    allocation: "autre",
    liters: 35,
    unitPrice: 11.8,
    exitNumber: "BS-003",
    status: "valide",
    hasDocument: false,
    enteredByUserId: "user-ayoub",
  },
];

export const personnelTimesheets: PersonnelTimesheet[] = [
  {
    id: "personnel-timesheet-01",
    date: "2026-05-12",
    chantierId: "chantier-genie-meknes",
    employeeId: "employee-omar",
    hoursWorked: 9,
    dayType: "normal",
    appliedRemunerationType: "jour",
    appliedDailyRate: 160,
    status: "valide",
  },
  {
    id: "personnel-timesheet-02",
    date: "2026-05-12",
    chantierId: "chantier-genie-meknes",
    employeeId: "employee-yassine",
    hoursWorked: 9,
    dayType: "normal",
    appliedRemunerationType: "mois",
    appliedMonthlySalary: 5200,
    status: "valide",
  },
];

export const personnelAdvances: PersonnelAdvance[] = [
  {
    id: "personnel-advance-01",
    date: "2026-05-15",
    chantierId: "chantier-genie-meknes",
    employeeId: "employee-omar",
    amount: 500,
    transactionId: "transaction-avance-01",
    status: "valide",
  },
];

export const equipmentTimesheets: EquipmentTimesheet[] = [
  {
    id: "equipment-timesheet-01",
    date: "2026-05-12",
    chantierId: "chantier-genie-meknes",
    equipmentId: "equipment-pelle-01",
    driver: "Said",
    hoursWorked: 8,
    activityType: "production",
    appliedBillingMode: "heure",
    appliedHourlyRate: 350,
    status: "valide",
  },
  {
    id: "equipment-timesheet-02",
    date: "2026-05-12",
    chantierId: "chantier-genie-meknes",
    equipmentId: "equipment-niveleuse-01",
    driver: "Mustapha",
    daysBilled: 1,
    activityType: "reglage",
    appliedBillingMode: "jour",
    appliedDailyRate: 2600,
    status: "valide",
  },
  {
    id: "equipment-timesheet-03",
    date: "2026-05-13",
    chantierId: "chantier-genie-meknes",
    equipmentId: "equipment-camion-01",
    driver: "Hamid",
    hoursWorked: 7,
    activityType: "transport",
    appliedBillingMode: "heure",
    status: "soumis",
  },
];

export const productions: Production[] = [
  {
    id: "production-01",
    chantierId: "chantier-genie-meknes",
    date: "2026-05-12",
    voie: "Voie A",
    tranche: "T1",
    troncon: "PK 0+000 - PK 0+180",
    workType: "Deblai",
    equipmentId: "equipment-pelle-01",
    driver: "Said",
    length: 180,
    width: 7,
    depth: 0.45,
    quantity: 567,
    unit: "m3",
    hours: 8,
    status: "valide",
  },
  {
    id: "production-02",
    chantierId: "chantier-genie-meknes",
    date: "2026-05-13",
    voie: "Voie B",
    tranche: "T1",
    troncon: "PK 0+180 - PK 0+320",
    workType: "Reglage",
    equipmentId: "equipment-niveleuse-01",
    driver: "Mustapha",
    length: 140,
    width: 6.5,
    quantity: 910,
    unit: "m2",
    hours: 7,
    status: "soumis",
  },
];

export const activeChantier = chantiers[0];

export const dashboardSummary = buildDashboardSummary({
  chantierId: activeChantier.id,
  transactions,
  gasoilEntries,
  gasoilExits,
  personnelTimesheets,
  personnelAdvances,
  equipment,
  equipmentTimesheets,
  highPaymentThreshold: 30000,
});

export const mobileToday = {
  user: users.find((user) => user.id === "user-ayoub") ?? users[0],
  chantier: activeChantier,
  submittedGasoilExits: gasoilExits.filter((exit) => exit.enteredByUserId === "user-ayoub" && exit.status === "soumis"),
  rejectedItems: [],
  equipmentTimesheets: equipmentTimesheets.filter((timesheet) => timesheet.status === "soumis"),
};

export const recentEquipmentCosts = equipmentTimesheets.map((timesheet) => ({
  timesheet,
  equipment: equipment.find((item) => item.id === timesheet.equipmentId),
  cost: calculateEquipmentTimesheetCost(timesheet),
}));

export const recentPersonnelCosts = personnelTimesheets.map((timesheet) => ({
  timesheet,
  employee: employees.find((item) => item.id === timesheet.employeeId),
  due: calculatePersonnelTimesheetDue(timesheet),
}));
